/// <reference path="../types/common.d.ts" />
export const MAP_SPEED_NORMAL = () => ConvertGameSpeed(2);

export const bj_PI = Math.PI;
export const bj_E = Math.E;
export const bj_CELLWIDTH = 128.0;
export const bj_CLIFFHEIGHT = 128.0;
export const bj_UNIT_FACING = 270.0;
export const bj_RADTODEG = 180.0 / bj_PI;
export const bj_DEGTORAD = bj_PI / 180.0;
export const bj_TEXT_DELAY_QUEST = 20.0;
export const bj_TEXT_DELAY_QUESTUPDATE = 20.0;
export const bj_TEXT_DELAY_QUESTDONE = 20.0;
export const bj_TEXT_DELAY_QUESTFAILED = 20.0;
export const bj_TEXT_DELAY_QUESTREQUIREMENT = 20.0;
export const bj_TEXT_DELAY_MISSIONFAILED = 20.0;
export const bj_TEXT_DELAY_ALWAYSHINT = 12.0;
export const bj_TEXT_DELAY_HINT = 12.0;
export const bj_TEXT_DELAY_SECRET = 10.0;
export const bj_TEXT_DELAY_UNITACQUIRED = 15.0;
export const bj_TEXT_DELAY_UNITAVAILABLE = 10.0;
export const bj_TEXT_DELAY_ITEMACQUIRED = 10.0;
export const bj_TEXT_DELAY_WARNING = 12.0;
export const bj_QUEUE_DELAY_QUEST = 5.0;
export const bj_QUEUE_DELAY_HINT = 5.0;
export const bj_QUEUE_DELAY_SECRET = 3.0;
export const bj_HANDICAP_EASY = 60.0;
export const bj_GAME_STARTED_THRESHOLD = 0.01;
export const bj_WAIT_FOR_COND_MIN_INTERVAL = 0.1;
export const bj_POLLED_WAIT_INTERVAL = 0.1;
export const bj_POLLED_WAIT_SKIP_THRESHOLD = 2.0;
export const bj_MAX_INVENTORY = 6;
export const bj_MAX_PLAYERS = 12;
export const bj_PLAYER_NEUTRAL_VICTIM = 13;
export const bj_PLAYER_NEUTRAL_EXTRA = 14;
export const bj_MAX_PLAYER_SLOTS = 16;
export const bj_MAX_SKELETONS = 25;
export const bj_MAX_STOCK_ITEM_SLOTS = 11;
export const bj_MAX_STOCK_UNIT_SLOTS = 11;
export const bj_MAX_ITEM_LEVEL = 10;
export const bj_TOD_DAWN = 6.0;
export const bj_TOD_DUSK = 18.0;
export const bj_MELEE_STARTING_TOD = 8.0;
export const bj_MELEE_STARTING_GOLD_V0 = 750;
export const bj_MELEE_STARTING_GOLD_V1 = 500;
export const bj_MELEE_STARTING_LUMBER_V0 = 200;
export const bj_MELEE_STARTING_LUMBER_V1 = 150;
export const bj_MELEE_STARTING_HERO_TOKENS = 1;
export const bj_MELEE_HERO_LIMIT = 3;
export const bj_MELEE_HERO_TYPE_LIMIT = 1;
export const bj_MELEE_MINE_SEARCH_RADIUS = 2000;
export const bj_MELEE_CLEAR_UNITS_RADIUS = 1500;
export const bj_MELEE_CRIPPLE_TIMEOUT = 120.0;
export const bj_MELEE_CRIPPLE_MSG_DURATION = 20.0;
export const bj_MELEE_MAX_TWINKED_HEROES_V0 = 3;
export const bj_MELEE_MAX_TWINKED_HEROES_V1 = 1;
export const bj_CREEP_ITEM_DELAY = 0.5;
export const bj_STOCK_RESTOCK_INITIAL_DELAY = 120;
export const bj_STOCK_RESTOCK_INTERVAL = 30;
export const bj_STOCK_MAX_ITERATIONS = 20;
export const bj_MAX_DEST_IN_REGION_EVENTS = 64;
export const bj_CAMERA_MIN_FARZ = 100;
export const bj_CAMERA_DEFAULT_DISTANCE = 1650;
export const bj_CAMERA_DEFAULT_FARZ = 5000;
export const bj_CAMERA_DEFAULT_AOA = 304;
export const bj_CAMERA_DEFAULT_FOV = 70;
export const bj_CAMERA_DEFAULT_ROLL = 0;
export const bj_CAMERA_DEFAULT_ROTATION = 90;
export const bj_RESCUE_PING_TIME = 2.0;
export const bj_NOTHING_SOUND_DURATION = 5.0;
export const bj_TRANSMISSION_PING_TIME = 1.0;
export const bj_TRANSMISSION_IND_RED = 255;
export const bj_TRANSMISSION_IND_BLUE = 255;
export const bj_TRANSMISSION_IND_GREEN = 255;
export const bj_TRANSMISSION_IND_ALPHA = 255;
export const bj_TRANSMISSION_PORT_HANGTIME = 1.5;
export const bj_CINEMODE_INTERFACEFADE = 0.5;
export const bj_CINEMODE_GAMESPEED = MAP_SPEED_NORMAL;
export const bj_CINEMODE_VOLUME_UNITMOVEMENT = 0.4;
export const bj_CINEMODE_VOLUME_UNITSOUNDS = 0.0;
export const bj_CINEMODE_VOLUME_COMBAT = 0.4;
export const bj_CINEMODE_VOLUME_SPELLS = 0.4;
export const bj_CINEMODE_VOLUME_UI = 0.0;
export const bj_CINEMODE_VOLUME_MUSIC = 0.55;
export const bj_CINEMODE_VOLUME_AMBIENTSOUNDS = 1.0;
export const bj_CINEMODE_VOLUME_FIRE = 0.6;
export const bj_SPEECH_VOLUME_UNITMOVEMENT = 0.25;
export const bj_SPEECH_VOLUME_UNITSOUNDS = 0.0;
export const bj_SPEECH_VOLUME_COMBAT = 0.25;
export const bj_SPEECH_VOLUME_SPELLS = 0.25;
export const bj_SPEECH_VOLUME_UI = 0.0;
export const bj_SPEECH_VOLUME_MUSIC = 0.55;
export const bj_SPEECH_VOLUME_AMBIENTSOUNDS = 1.0;
export const bj_SPEECH_VOLUME_FIRE = 0.6;
export const bj_SMARTPAN_TRESHOLD_PAN = 500;
export const bj_SMARTPAN_TRESHOLD_SNAP = 3500;
export const bj_MAX_QUEUED_TRIGGERS = 100;
export const bj_QUEUED_TRIGGER_TIMEOUT = 180.0;
export const bj_CAMPAIGN_INDEX_T = 0;
export const bj_CAMPAIGN_INDEX_H = 1;
export const bj_CAMPAIGN_INDEX_U = 2;
export const bj_CAMPAIGN_INDEX_O = 3;
export const bj_CAMPAIGN_INDEX_N = 4;
export const bj_CAMPAIGN_INDEX_XN = 5;
export const bj_CAMPAIGN_INDEX_XH = 6;
export const bj_CAMPAIGN_INDEX_XU = 7;
export const bj_CAMPAIGN_INDEX_XO = 8;
export const bj_CAMPAIGN_OFFSET_T = 0;
export const bj_CAMPAIGN_OFFSET_H = 1;
export const bj_CAMPAIGN_OFFSET_U = 2;
export const bj_CAMPAIGN_OFFSET_O = 3;
export const bj_CAMPAIGN_OFFSET_N = 4;
export const bj_CAMPAIGN_OFFSET_XN = 0;
export const bj_CAMPAIGN_OFFSET_XH = 1;
export const bj_CAMPAIGN_OFFSET_XU = 2;
export const bj_CAMPAIGN_OFFSET_XO = 3;
export const bj_MISSION_INDEX_T00 = bj_CAMPAIGN_OFFSET_T * 1000 + 0;
export const bj_MISSION_INDEX_T01 = bj_CAMPAIGN_OFFSET_T * 1000 + 1;
export const bj_MISSION_INDEX_H00 = bj_CAMPAIGN_OFFSET_H * 1000 + 0;
export const bj_MISSION_INDEX_H01 = bj_CAMPAIGN_OFFSET_H * 1000 + 1;
export const bj_MISSION_INDEX_H02 = bj_CAMPAIGN_OFFSET_H * 1000 + 2;
export const bj_MISSION_INDEX_H03 = bj_CAMPAIGN_OFFSET_H * 1000 + 3;
export const bj_MISSION_INDEX_H04 = bj_CAMPAIGN_OFFSET_H * 1000 + 4;
export const bj_MISSION_INDEX_H05 = bj_CAMPAIGN_OFFSET_H * 1000 + 5;
export const bj_MISSION_INDEX_H06 = bj_CAMPAIGN_OFFSET_H * 1000 + 6;
export const bj_MISSION_INDEX_H07 = bj_CAMPAIGN_OFFSET_H * 1000 + 7;
export const bj_MISSION_INDEX_H08 = bj_CAMPAIGN_OFFSET_H * 1000 + 8;
export const bj_MISSION_INDEX_H09 = bj_CAMPAIGN_OFFSET_H * 1000 + 9;
export const bj_MISSION_INDEX_H10 = bj_CAMPAIGN_OFFSET_H * 1000 + 10;
export const bj_MISSION_INDEX_H11 = bj_CAMPAIGN_OFFSET_H * 1000 + 11;
export const bj_MISSION_INDEX_U00 = bj_CAMPAIGN_OFFSET_U * 1000 + 0;
export const bj_MISSION_INDEX_U01 = bj_CAMPAIGN_OFFSET_U * 1000 + 1;
export const bj_MISSION_INDEX_U02 = bj_CAMPAIGN_OFFSET_U * 1000 + 2;
export const bj_MISSION_INDEX_U03 = bj_CAMPAIGN_OFFSET_U * 1000 + 3;
export const bj_MISSION_INDEX_U05 = bj_CAMPAIGN_OFFSET_U * 1000 + 4;
export const bj_MISSION_INDEX_U07 = bj_CAMPAIGN_OFFSET_U * 1000 + 5;
export const bj_MISSION_INDEX_U08 = bj_CAMPAIGN_OFFSET_U * 1000 + 6;
export const bj_MISSION_INDEX_U09 = bj_CAMPAIGN_OFFSET_U * 1000 + 7;
export const bj_MISSION_INDEX_U10 = bj_CAMPAIGN_OFFSET_U * 1000 + 8;
export const bj_MISSION_INDEX_U11 = bj_CAMPAIGN_OFFSET_U * 1000 + 9;
export const bj_MISSION_INDEX_O00 = bj_CAMPAIGN_OFFSET_O * 1000 + 0;
export const bj_MISSION_INDEX_O01 = bj_CAMPAIGN_OFFSET_O * 1000 + 1;
export const bj_MISSION_INDEX_O02 = bj_CAMPAIGN_OFFSET_O * 1000 + 2;
export const bj_MISSION_INDEX_O03 = bj_CAMPAIGN_OFFSET_O * 1000 + 3;
export const bj_MISSION_INDEX_O04 = bj_CAMPAIGN_OFFSET_O * 1000 + 4;
export const bj_MISSION_INDEX_O05 = bj_CAMPAIGN_OFFSET_O * 1000 + 5;
export const bj_MISSION_INDEX_O06 = bj_CAMPAIGN_OFFSET_O * 1000 + 6;
export const bj_MISSION_INDEX_O07 = bj_CAMPAIGN_OFFSET_O * 1000 + 7;
export const bj_MISSION_INDEX_O08 = bj_CAMPAIGN_OFFSET_O * 1000 + 8;
export const bj_MISSION_INDEX_O09 = bj_CAMPAIGN_OFFSET_O * 1000 + 9;
export const bj_MISSION_INDEX_O10 = bj_CAMPAIGN_OFFSET_O * 1000 + 10;
export const bj_MISSION_INDEX_N00 = bj_CAMPAIGN_OFFSET_N * 1000 + 0;
export const bj_MISSION_INDEX_N01 = bj_CAMPAIGN_OFFSET_N * 1000 + 1;
export const bj_MISSION_INDEX_N02 = bj_CAMPAIGN_OFFSET_N * 1000 + 2;
export const bj_MISSION_INDEX_N03 = bj_CAMPAIGN_OFFSET_N * 1000 + 3;
export const bj_MISSION_INDEX_N04 = bj_CAMPAIGN_OFFSET_N * 1000 + 4;
export const bj_MISSION_INDEX_N05 = bj_CAMPAIGN_OFFSET_N * 1000 + 5;
export const bj_MISSION_INDEX_N06 = bj_CAMPAIGN_OFFSET_N * 1000 + 6;
export const bj_MISSION_INDEX_N07 = bj_CAMPAIGN_OFFSET_N * 1000 + 7;
export const bj_MISSION_INDEX_N08 = bj_CAMPAIGN_OFFSET_N * 1000 + 8;
export const bj_MISSION_INDEX_N09 = bj_CAMPAIGN_OFFSET_N * 1000 + 9;
export const bj_MISSION_INDEX_XN00 = bj_CAMPAIGN_OFFSET_XN * 1000 + 0;
export const bj_MISSION_INDEX_XN01 = bj_CAMPAIGN_OFFSET_XN * 1000 + 1;
export const bj_MISSION_INDEX_XN02 = bj_CAMPAIGN_OFFSET_XN * 1000 + 2;
export const bj_MISSION_INDEX_XN03 = bj_CAMPAIGN_OFFSET_XN * 1000 + 3;
export const bj_MISSION_INDEX_XN04 = bj_CAMPAIGN_OFFSET_XN * 1000 + 4;
export const bj_MISSION_INDEX_XN05 = bj_CAMPAIGN_OFFSET_XN * 1000 + 5;
export const bj_MISSION_INDEX_XN06 = bj_CAMPAIGN_OFFSET_XN * 1000 + 6;
export const bj_MISSION_INDEX_XN07 = bj_CAMPAIGN_OFFSET_XN * 1000 + 7;
export const bj_MISSION_INDEX_XN08 = bj_CAMPAIGN_OFFSET_XN * 1000 + 8;
export const bj_MISSION_INDEX_XN09 = bj_CAMPAIGN_OFFSET_XN * 1000 + 9;
export const bj_MISSION_INDEX_XN10 = bj_CAMPAIGN_OFFSET_XN * 1000 + 10;
export const bj_MISSION_INDEX_XH00 = bj_CAMPAIGN_OFFSET_XH * 1000 + 0;
export const bj_MISSION_INDEX_XH01 = bj_CAMPAIGN_OFFSET_XH * 1000 + 1;
export const bj_MISSION_INDEX_XH02 = bj_CAMPAIGN_OFFSET_XH * 1000 + 2;
export const bj_MISSION_INDEX_XH03 = bj_CAMPAIGN_OFFSET_XH * 1000 + 3;
export const bj_MISSION_INDEX_XH04 = bj_CAMPAIGN_OFFSET_XH * 1000 + 4;
export const bj_MISSION_INDEX_XH05 = bj_CAMPAIGN_OFFSET_XH * 1000 + 5;
export const bj_MISSION_INDEX_XH06 = bj_CAMPAIGN_OFFSET_XH * 1000 + 6;
export const bj_MISSION_INDEX_XH07 = bj_CAMPAIGN_OFFSET_XH * 1000 + 7;
export const bj_MISSION_INDEX_XH08 = bj_CAMPAIGN_OFFSET_XH * 1000 + 8;
export const bj_MISSION_INDEX_XH09 = bj_CAMPAIGN_OFFSET_XH * 1000 + 9;
export const bj_MISSION_INDEX_XU00 = bj_CAMPAIGN_OFFSET_XU * 1000 + 0;
export const bj_MISSION_INDEX_XU01 = bj_CAMPAIGN_OFFSET_XU * 1000 + 1;
export const bj_MISSION_INDEX_XU02 = bj_CAMPAIGN_OFFSET_XU * 1000 + 2;
export const bj_MISSION_INDEX_XU03 = bj_CAMPAIGN_OFFSET_XU * 1000 + 3;
export const bj_MISSION_INDEX_XU04 = bj_CAMPAIGN_OFFSET_XU * 1000 + 4;
export const bj_MISSION_INDEX_XU05 = bj_CAMPAIGN_OFFSET_XU * 1000 + 5;
export const bj_MISSION_INDEX_XU06 = bj_CAMPAIGN_OFFSET_XU * 1000 + 6;
export const bj_MISSION_INDEX_XU07 = bj_CAMPAIGN_OFFSET_XU * 1000 + 7;
export const bj_MISSION_INDEX_XU08 = bj_CAMPAIGN_OFFSET_XU * 1000 + 8;
export const bj_MISSION_INDEX_XU09 = bj_CAMPAIGN_OFFSET_XU * 1000 + 9;
export const bj_MISSION_INDEX_XU10 = bj_CAMPAIGN_OFFSET_XU * 1000 + 10;
export const bj_MISSION_INDEX_XU11 = bj_CAMPAIGN_OFFSET_XU * 1000 + 11;
export const bj_MISSION_INDEX_XU12 = bj_CAMPAIGN_OFFSET_XU * 1000 + 12;
export const bj_MISSION_INDEX_XU13 = bj_CAMPAIGN_OFFSET_XU * 1000 + 13;
export const bj_MISSION_INDEX_XO00 = bj_CAMPAIGN_OFFSET_XO * 1000 + 0;
export const bj_CINEMATICINDEX_TOP = 0;
export const bj_CINEMATICINDEX_HOP = 1;
export const bj_CINEMATICINDEX_HED = 2;
export const bj_CINEMATICINDEX_OOP = 3;
export const bj_CINEMATICINDEX_OED = 4;
export const bj_CINEMATICINDEX_UOP = 5;
export const bj_CINEMATICINDEX_UED = 6;
export const bj_CINEMATICINDEX_NOP = 7;
export const bj_CINEMATICINDEX_NED = 8;
export const bj_CINEMATICINDEX_XOP = 9;
export const bj_CINEMATICINDEX_XED = 10;
export const bj_ALLIANCE_UNALLIED = 0;
export const bj_ALLIANCE_UNALLIED_VISION = 1;
export const bj_ALLIANCE_ALLIED = 2;
export const bj_ALLIANCE_ALLIED_VISION = 3;
export const bj_ALLIANCE_ALLIED_UNITS = 4;
export const bj_ALLIANCE_ALLIED_ADVUNITS = 5;
export const bj_ALLIANCE_NEUTRAL = 6;
export const bj_ALLIANCE_NEUTRAL_VISION = 7;
export const bj_KEYEVENTTYPE_DEPRESS = 0;
export const bj_KEYEVENTTYPE_RELEASE = 1;
export const bj_KEYEVENTKEY_LEFT = 0;
export const bj_KEYEVENTKEY_RIGHT = 1;
export const bj_KEYEVENTKEY_DOWN = 2;
export const bj_KEYEVENTKEY_UP = 3;
export const bj_TIMETYPE_ADD = 0;
export const bj_TIMETYPE_SET = 1;
export const bj_TIMETYPE_SUB = 2;
export const bj_CAMERABOUNDS_ADJUST_ADD = 0;
export const bj_CAMERABOUNDS_ADJUST_SUB = 1;
export const bj_QUESTTYPE_REQ_DISCOVERED = 0;
export const bj_QUESTTYPE_REQ_UNDISCOVERED = 1;
export const bj_QUESTTYPE_OPT_DISCOVERED = 2;
export const bj_QUESTTYPE_OPT_UNDISCOVERED = 3;
export const bj_QUESTMESSAGE_DISCOVERED = 0;
export const bj_QUESTMESSAGE_UPDATED = 1;
export const bj_QUESTMESSAGE_COMPLETED = 2;
export const bj_QUESTMESSAGE_FAILED = 3;
export const bj_QUESTMESSAGE_REQUIREMENT = 4;
export const bj_QUESTMESSAGE_MISSIONFAILED = 5;
export const bj_QUESTMESSAGE_ALWAYSHINT = 6;
export const bj_QUESTMESSAGE_HINT = 7;
export const bj_QUESTMESSAGE_SECRET = 8;
export const bj_QUESTMESSAGE_UNITACQUIRED = 9;
export const bj_QUESTMESSAGE_UNITAVAILABLE = 10;
export const bj_QUESTMESSAGE_ITEMACQUIRED = 11;
export const bj_QUESTMESSAGE_WARNING = 12;
export const bj_SORTTYPE_SORTBYVALUE = 0;
export const bj_SORTTYPE_SORTBYPLAYER = 1;
export const bj_SORTTYPE_SORTBYLABEL = 2;
export const bj_CINEFADETYPE_FADEIN = 0;
export const bj_CINEFADETYPE_FADEOUT = 1;
export const bj_CINEFADETYPE_FADEOUTIN = 2;
export const bj_REMOVEBUFFS_POSITIVE = 0;
export const bj_REMOVEBUFFS_NEGATIVE = 1;
export const bj_REMOVEBUFFS_ALL = 2;
export const bj_REMOVEBUFFS_NONTLIFE = 3;
export const bj_BUFF_POLARITY_POSITIVE = 0;
export const bj_BUFF_POLARITY_NEGATIVE = 1;
export const bj_BUFF_POLARITY_EITHER = 2;
export const bj_BUFF_RESIST_MAGIC = 0;
export const bj_BUFF_RESIST_PHYSICAL = 1;
export const bj_BUFF_RESIST_EITHER = 2;
export const bj_BUFF_RESIST_BOTH = 3;
export const bj_HEROSTAT_STR = 0;
export const bj_HEROSTAT_AGI = 1;
export const bj_HEROSTAT_INT = 2;
export const bj_MODIFYMETHOD_ADD = 0;
export const bj_MODIFYMETHOD_SUB = 1;
export const bj_MODIFYMETHOD_SET = 2;
export const bj_UNIT_STATE_METHOD_ABSOLUTE = 0;
export const bj_UNIT_STATE_METHOD_RELATIVE = 1;
export const bj_UNIT_STATE_METHOD_DEFAULTS = 2;
export const bj_UNIT_STATE_METHOD_MAXIMUM = 3;
export const bj_GATEOPERATION_CLOSE = 0;
export const bj_GATEOPERATION_OPEN = 1;
export const bj_GATEOPERATION_DESTROY = 2;
export const bj_GAMECACHE_BOOLEAN = 0;
export const bj_GAMECACHE_INTEGER = 1;
export const bj_GAMECACHE_REAL = 2;
export const bj_GAMECACHE_UNIT = 3;
export const bj_GAMECACHE_STRING = 4;
export const bj_ITEM_STATUS_HIDDEN = 0;
export const bj_ITEM_STATUS_OWNED = 1;
export const bj_ITEM_STATUS_INVULNERABLE = 2;
export const bj_ITEM_STATUS_POWERUP = 3;
export const bj_ITEM_STATUS_SELLABLE = 4;
export const bj_ITEM_STATUS_PAWNABLE = 5;
export const bj_ITEMCODE_STATUS_POWERUP = 0;
export const bj_ITEMCODE_STATUS_SELLABLE = 1;
export const bj_ITEMCODE_STATUS_PAWNABLE = 2;
export const bj_MINIMAPPINGSTYLE_SIMPLE = 0;
export const bj_MINIMAPPINGSTYLE_FLASHY = 1;
export const bj_MINIMAPPINGSTYLE_ATTACK = 2;
export const bj_CORPSE_MAX_DEATH_TIME = 8.0;
export const bj_CORPSETYPE_FLESH = 0;
export const bj_CORPSETYPE_BONE = 1;
export const bj_ELEVATOR_BLOCKER_CODE = "DTep";
export const bj_ELEVATOR_CODE01 = "DTrf";
export const bj_ELEVATOR_CODE02 = "DTrx";
export const bj_ELEVATOR_WALL_TYPE_ALL = 0;
export const bj_ELEVATOR_WALL_TYPE_EAST = 1;
export const bj_ELEVATOR_WALL_TYPE_NORTH = 2;
export const bj_ELEVATOR_WALL_TYPE_SOUTH = 3;
export const bj_ELEVATOR_WALL_TYPE_WEST = 4;
export const bj_MELEE_MAX_TWINKED_HEROES = 0;
export const bj_mapInitialPlayableArea = null;
export const bj_mapInitialCameraBounds = null;
export const bj_forLoopAIndex = 0;
export const bj_forLoopBIndex = 0;
export const bj_forLoopAIndexEnd = 0;
export const bj_forLoopBIndexEnd = 0;
export const bj_slotControlReady = false;
export const bj_gameStartedTimer = null;
export const bj_gameStarted = false;
export const bj_isSinglePlayer = false;
export const bj_dncSoundsDay = null;
export const bj_dncSoundsNight = null;
export const bj_dayAmbientSound = null;
export const bj_nightAmbientSound = null;
export const bj_dncSoundsDawn = null;
export const bj_dncSoundsDusk = null;
export const bj_dawnSound = null;
export const bj_duskSound = null;
export const bj_useDawnDuskSounds = true;
export const bj_dncIsDaytime = false;
export const bj_rescueSound = null;
export const bj_questDiscoveredSound = null;
export const bj_questUpdatedSound = null;
export const bj_questCompletedSound = null;
export const bj_questFailedSound = null;
export const bj_questHintSound = null;
export const bj_questSecretSound = null;
export const bj_questItemAcquiredSound = null;
export const bj_questWarningSound = null;
export const bj_victoryDialogSound = null;
export const bj_defeatDialogSound = null;
export const bj_rescueUnitBehavior = null;
export const bj_rescueChangeColorUnit = true;
export const bj_rescueChangeColorBldg = true;
export const bj_cineSceneEndingTimer = null;
export const bj_cineSceneLastSound = null;
export const bj_cineSceneBeingSkipped = null;
export const bj_cineModePriorSpeed = MAP_SPEED_NORMAL;
export const bj_cineModePriorFogSetting = false;
export const bj_cineModePriorMaskSetting = false;
export const bj_cineModeAlreadyIn = false;
export const bj_cineModePriorDawnDusk = false;
export const bj_cineModeSavedSeed = 0;
export const bj_cineFadeFinishTimer = null;
export const bj_cineFadeContinueTimer = null;
export const bj_cineFadeContinueRed = 0;
export const bj_cineFadeContinueGreen = 0;
export const bj_cineFadeContinueBlue = 0;
export const bj_cineFadeContinueTrans = 0;
export const bj_cineFadeContinueDuration = 0;
export const bj_cineFadeContinueTex = "";
export const JASS_MAX_ARRAY_SIZE = 8192;
export const PLAYER_NEUTRAL_PASSIVE = 15;
export const PLAYER_NEUTRAL_AGGRESSIVE = 12;
export const PLAYER_COLOR_RED = () => ConvertPlayerColor(0);
export const PLAYER_COLOR_BLUE = () => ConvertPlayerColor(1);
export const PLAYER_COLOR_CYAN = () => ConvertPlayerColor(2);
export const PLAYER_COLOR_PURPLE = () => ConvertPlayerColor(3);
export const PLAYER_COLOR_YELLOW = () => ConvertPlayerColor(4);
export const PLAYER_COLOR_ORANGE = () => ConvertPlayerColor(5);
export const PLAYER_COLOR_GREEN = () => ConvertPlayerColor(6);
export const PLAYER_COLOR_PINK = () => ConvertPlayerColor(7);
export const PLAYER_COLOR_LIGHT_GRAY = () => ConvertPlayerColor(8);
export const PLAYER_COLOR_LIGHT_BLUE = () => ConvertPlayerColor(9);
export const PLAYER_COLOR_AQUA = () => ConvertPlayerColor(10);
export const PLAYER_COLOR_BROWN = () => ConvertPlayerColor(11);
export const PLAYER_COLOR_BLACK = () => ConvertPlayerColor(12);
export const RACE_HUMAN = () => ConvertRace(1);
export const RACE_ORC = () => ConvertRace(2);
export const RACE_UNDEAD = () => ConvertRace(3);
export const RACE_NIGHTELF = () => ConvertRace(4);
export const RACE_DEMON = () => ConvertRace(5);
export const RACE_OTHER = () => ConvertRace(7);
export const PLAYER_GAME_RESULT_VICTORY = () => ConvertPlayerGameResult(0);
export const PLAYER_GAME_RESULT_DEFEAT = () => ConvertPlayerGameResult(1);
export const PLAYER_GAME_RESULT_TIE = () => ConvertPlayerGameResult(2);
export const PLAYER_GAME_RESULT_NEUTRAL = () => ConvertPlayerGameResult(3);
export const ALLIANCE_PASSIVE = () => ConvertAllianceType(0);
export const ALLIANCE_HELP_REQUEST = () => ConvertAllianceType(1);
export const ALLIANCE_HELP_RESPONSE = () => ConvertAllianceType(2);
export const ALLIANCE_SHARED_XP = () => ConvertAllianceType(3);
export const ALLIANCE_SHARED_SPELLS = () => ConvertAllianceType(4);
export const ALLIANCE_SHARED_VISION = () => ConvertAllianceType(5);
export const ALLIANCE_SHARED_CONTROL = () => ConvertAllianceType(6);
export const ALLIANCE_SHARED_ADVANCED_CONTROL = () => ConvertAllianceType(7);
export const ALLIANCE_RESCUABLE = () => ConvertAllianceType(8);
export const ALLIANCE_SHARED_VISION_FORCED = () => ConvertAllianceType(9);
export const VERSION_REIGN_OF_CHAOS = () => ConvertVersion(0);
export const VERSION_FROZEN_THRONE = () => ConvertVersion(1);
export const ATTACK_TYPE_NORMAL = () => ConvertAttackType(0);
export const ATTACK_TYPE_MELEE = () => ConvertAttackType(1);
export const ATTACK_TYPE_PIERCE = () => ConvertAttackType(2);
export const ATTACK_TYPE_SIEGE = () => ConvertAttackType(3);
export const ATTACK_TYPE_MAGIC = () => ConvertAttackType(4);
export const ATTACK_TYPE_CHAOS = () => ConvertAttackType(5);
export const ATTACK_TYPE_HERO = () => ConvertAttackType(6);
export const DAMAGE_TYPE_UNKNOWN = () => ConvertDamageType(0);
export const DAMAGE_TYPE_NORMAL = () => ConvertDamageType(4);
export const DAMAGE_TYPE_ENHANCED = () => ConvertDamageType(5);
export const DAMAGE_TYPE_FIRE = () => ConvertDamageType(8);
export const DAMAGE_TYPE_COLD = () => ConvertDamageType(9);
export const DAMAGE_TYPE_LIGHTNING = () => ConvertDamageType(10);
export const DAMAGE_TYPE_POISON = () => ConvertDamageType(11);
export const DAMAGE_TYPE_DISEASE = () => ConvertDamageType(12);
export const DAMAGE_TYPE_DIVINE = () => ConvertDamageType(13);
export const DAMAGE_TYPE_MAGIC = () => ConvertDamageType(14);
export const DAMAGE_TYPE_SONIC = () => ConvertDamageType(15);
export const DAMAGE_TYPE_ACID = () => ConvertDamageType(16);
export const DAMAGE_TYPE_FORCE = () => ConvertDamageType(17);
export const DAMAGE_TYPE_DEATH = () => ConvertDamageType(18);
export const DAMAGE_TYPE_MIND = () => ConvertDamageType(19);
export const DAMAGE_TYPE_PLANT = () => ConvertDamageType(20);
export const DAMAGE_TYPE_DEFENSIVE = () => ConvertDamageType(21);
export const DAMAGE_TYPE_DEMOLITION = () => ConvertDamageType(22);
export const DAMAGE_TYPE_SLOW_POISON = () => ConvertDamageType(23);
export const DAMAGE_TYPE_SPIRIT_LINK = () => ConvertDamageType(24);
export const DAMAGE_TYPE_SHADOW_STRIKE = () => ConvertDamageType(25);
export const DAMAGE_TYPE_UNIVERSAL = () => ConvertDamageType(26);
export const WEAPON_TYPE_WHOKNOWS = () => ConvertWeaponType(0);
export const WEAPON_TYPE_METAL_LIGHT_CHOP = () => ConvertWeaponType(1);
export const WEAPON_TYPE_METAL_MEDIUM_CHOP = () => ConvertWeaponType(2);
export const WEAPON_TYPE_METAL_HEAVY_CHOP = () => ConvertWeaponType(3);
export const WEAPON_TYPE_METAL_LIGHT_SLICE = () => ConvertWeaponType(4);
export const WEAPON_TYPE_METAL_MEDIUM_SLICE = () => ConvertWeaponType(5);
export const WEAPON_TYPE_METAL_HEAVY_SLICE = () => ConvertWeaponType(6);
export const WEAPON_TYPE_METAL_MEDIUM_BASH = () => ConvertWeaponType(7);
export const WEAPON_TYPE_METAL_HEAVY_BASH = () => ConvertWeaponType(8);
export const WEAPON_TYPE_METAL_MEDIUM_STAB = () => ConvertWeaponType(9);
export const WEAPON_TYPE_METAL_HEAVY_STAB = () => ConvertWeaponType(10);
export const WEAPON_TYPE_WOOD_LIGHT_SLICE = () => ConvertWeaponType(11);
export const WEAPON_TYPE_WOOD_MEDIUM_SLICE = () => ConvertWeaponType(12);
export const WEAPON_TYPE_WOOD_HEAVY_SLICE = () => ConvertWeaponType(13);
export const WEAPON_TYPE_WOOD_LIGHT_BASH = () => ConvertWeaponType(14);
export const WEAPON_TYPE_WOOD_MEDIUM_BASH = () => ConvertWeaponType(15);
export const WEAPON_TYPE_WOOD_HEAVY_BASH = () => ConvertWeaponType(16);
export const WEAPON_TYPE_WOOD_LIGHT_STAB = () => ConvertWeaponType(17);
export const WEAPON_TYPE_WOOD_MEDIUM_STAB = () => ConvertWeaponType(18);
export const WEAPON_TYPE_CLAW_LIGHT_SLICE = () => ConvertWeaponType(19);
export const WEAPON_TYPE_CLAW_MEDIUM_SLICE = () => ConvertWeaponType(20);
export const WEAPON_TYPE_CLAW_HEAVY_SLICE = () => ConvertWeaponType(21);
export const WEAPON_TYPE_AXE_MEDIUM_CHOP = () => ConvertWeaponType(22);
export const WEAPON_TYPE_ROCK_HEAVY_BASH = () => ConvertWeaponType(23);
export const PATHING_TYPE_ANY = () => ConvertPathingType(0);
export const PATHING_TYPE_WALKABILITY = () => ConvertPathingType(1);
export const PATHING_TYPE_FLYABILITY = () => ConvertPathingType(2);
export const PATHING_TYPE_BUILDABILITY = () => ConvertPathingType(3);
export const PATHING_TYPE_PEONHARVESTPATHING = () => ConvertPathingType(4);
export const PATHING_TYPE_BLIGHTPATHING = () => ConvertPathingType(5);
export const PATHING_TYPE_FLOATABILITY = () => ConvertPathingType(6);
export const PATHING_TYPE_AMPHIBIOUSPATHING = () => ConvertPathingType(7);
export const RACE_PREF_HUMAN = () => ConvertRacePref(1);
export const RACE_PREF_ORC = () => ConvertRacePref(2);
export const RACE_PREF_NIGHTELF = () => ConvertRacePref(4);
export const RACE_PREF_UNDEAD = () => ConvertRacePref(8);
export const RACE_PREF_DEMON = () => ConvertRacePref(16);
export const RACE_PREF_RANDOM = () => ConvertRacePref(32);
export const RACE_PREF_USER_SELECTABLE = () => ConvertRacePref(64);
export const MAP_CONTROL_USER = () => ConvertMapControl(0);
export const MAP_CONTROL_COMPUTER = () => ConvertMapControl(1);
export const MAP_CONTROL_RESCUABLE = () => ConvertMapControl(2);
export const MAP_CONTROL_NEUTRAL = () => ConvertMapControl(3);
export const MAP_CONTROL_CREEP = () => ConvertMapControl(4);
export const MAP_CONTROL_NONE = () => ConvertMapControl(5);
export const GAME_TYPE_MELEE = () => ConvertGameType(1);
export const GAME_TYPE_FFA = () => ConvertGameType(2);
export const GAME_TYPE_USE_MAP_SETTINGS = () => ConvertGameType(4);
export const GAME_TYPE_BLIZ = () => ConvertGameType(8);
export const GAME_TYPE_ONE_ON_ONE = () => ConvertGameType(16);
export const GAME_TYPE_TWO_TEAM_PLAY = () => ConvertGameType(32);
export const GAME_TYPE_THREE_TEAM_PLAY = () => ConvertGameType(64);
export const GAME_TYPE_FOUR_TEAM_PLAY = () => ConvertGameType(128);
export const MAP_FOG_HIDE_TERRAIN = () => ConvertMapFlag(1);
export const MAP_FOG_MAP_EXPLORED = () => ConvertMapFlag(2);
export const MAP_FOG_ALWAYS_VISIBLE = () => ConvertMapFlag(4);
export const MAP_USE_HANDICAPS = () => ConvertMapFlag(8);
export const MAP_OBSERVERS = () => ConvertMapFlag(16);
export const MAP_OBSERVERS_ON_DEATH = () => ConvertMapFlag(32);
export const MAP_FIXED_COLORS = () => ConvertMapFlag(128);
export const MAP_LOCK_RESOURCE_TRADING = () => ConvertMapFlag(256);
export const MAP_RESOURCE_TRADING_ALLIES_ONLY = () => ConvertMapFlag(512);
export const MAP_LOCK_ALLIANCE_CHANGES = () => ConvertMapFlag(1024);
export const MAP_ALLIANCE_CHANGES_HIDDEN = () => ConvertMapFlag(2048);
export const MAP_CHEATS = () => ConvertMapFlag(4096);
export const MAP_CHEATS_HIDDEN = () => ConvertMapFlag(8192);
export const MAP_LOCK_SPEED = () => ConvertMapFlag(8192 * 2);
export const MAP_LOCK_RANDOM_SEED = () => ConvertMapFlag(8192 * 4);
export const MAP_SHARED_ADVANCED_CONTROL = () => ConvertMapFlag(8192 * 8);
export const MAP_RANDOM_HERO = () => ConvertMapFlag(8192 * 16);
export const MAP_RANDOM_RACES = () => ConvertMapFlag(8192 * 32);
export const MAP_RELOADED = () => ConvertMapFlag(8192 * 64);
export const MAP_PLACEMENT_RANDOM = () => ConvertPlacement(0);
export const MAP_PLACEMENT_FIXED = () => ConvertPlacement(1);
export const MAP_PLACEMENT_USE_MAP_SETTINGS = () => ConvertPlacement(2);
export const MAP_PLACEMENT_TEAMS_TOGETHER = () => ConvertPlacement(3);
export const MAP_LOC_PRIO_LOW = () => ConvertStartLocPrio(0);
export const MAP_LOC_PRIO_HIGH = () => ConvertStartLocPrio(1);
export const MAP_LOC_PRIO_NOT = () => ConvertStartLocPrio(2);
export const MAP_DENSITY_NONE = () => ConvertMapDensity(0);
export const MAP_DENSITY_LIGHT = () => ConvertMapDensity(1);
export const MAP_DENSITY_MEDIUM = () => ConvertMapDensity(2);
export const MAP_DENSITY_HEAVY = () => ConvertMapDensity(3);
export const MAP_DIFFICULTY_EASY = () => ConvertGameDifficulty(0);
export const MAP_DIFFICULTY_NORMAL = () => ConvertGameDifficulty(1);
export const MAP_DIFFICULTY_HARD = () => ConvertGameDifficulty(2);
export const MAP_DIFFICULTY_INSANE = () => ConvertGameDifficulty(3);
export const MAP_SPEED_SLOWEST = () => ConvertGameSpeed(0);
export const MAP_SPEED_SLOW = () => ConvertGameSpeed(1);
// export const  MAP_SPEED_NORMAL = () => ConvertGameSpeed(2)
export const MAP_SPEED_FAST = () => ConvertGameSpeed(3);
export const MAP_SPEED_FASTEST = () => ConvertGameSpeed(4);
export const PLAYER_SLOT_STATE_EMPTY = () => ConvertPlayerSlotState(0);
export const PLAYER_SLOT_STATE_PLAYING = () => ConvertPlayerSlotState(1);
export const PLAYER_SLOT_STATE_LEFT = () => ConvertPlayerSlotState(2);
export const SOUND_VOLUMEGROUP_UNITMOVEMENT = () => ConvertVolumeGroup(0);
export const SOUND_VOLUMEGROUP_UNITSOUNDS = () => ConvertVolumeGroup(1);
export const SOUND_VOLUMEGROUP_COMBAT = () => ConvertVolumeGroup(2);
export const SOUND_VOLUMEGROUP_SPELLS = () => ConvertVolumeGroup(3);
export const SOUND_VOLUMEGROUP_UI = () => ConvertVolumeGroup(4);
export const SOUND_VOLUMEGROUP_MUSIC = () => ConvertVolumeGroup(5);
export const SOUND_VOLUMEGROUP_AMBIENTSOUNDS = () => ConvertVolumeGroup(6);
export const SOUND_VOLUMEGROUP_FIRE = () => ConvertVolumeGroup(7);
export const GAME_STATE_DIVINE_INTERVENTION = () => ConvertIGameState(0);
export const GAME_STATE_DISCONNECTED = () => ConvertIGameState(1);
export const GAME_STATE_TIME_OF_DAY = () => ConvertFGameState(2);
export const PLAYER_STATE_GAME_RESULT = () => ConvertPlayerState(0);
export const PLAYER_STATE_RESOURCE_GOLD = () => ConvertPlayerState(1);
export const PLAYER_STATE_RESOURCE_LUMBER = () => ConvertPlayerState(2);
export const PLAYER_STATE_RESOURCE_HERO_TOKENS = () => ConvertPlayerState(3);
export const PLAYER_STATE_RESOURCE_FOOD_CAP = () => ConvertPlayerState(4);
export const PLAYER_STATE_RESOURCE_FOOD_USED = () => ConvertPlayerState(5);
export const PLAYER_STATE_FOOD_CAP_CEILING = () => ConvertPlayerState(6);
export const PLAYER_STATE_GIVES_BOUNTY = () => ConvertPlayerState(7);
export const PLAYER_STATE_ALLIED_VICTORY = () => ConvertPlayerState(8);
export const PLAYER_STATE_PLACED = () => ConvertPlayerState(9);
export const PLAYER_STATE_OBSERVER_ON_DEATH = () => ConvertPlayerState(10);
export const PLAYER_STATE_OBSERVER = () => ConvertPlayerState(11);
export const PLAYER_STATE_UNFOLLOWABLE = () => ConvertPlayerState(12);
export const PLAYER_STATE_GOLD_UPKEEP_RATE = () => ConvertPlayerState(13);
export const PLAYER_STATE_LUMBER_UPKEEP_RATE = () => ConvertPlayerState(14);
export const PLAYER_STATE_GOLD_GATHERED = () => ConvertPlayerState(15);
export const PLAYER_STATE_LUMBER_GATHERED = () => ConvertPlayerState(16);
export const PLAYER_STATE_NO_CREEP_SLEEP = () => ConvertPlayerState(25);
export const UNIT_STATE_LIFE = () => ConvertUnitState(0);
export const UNIT_STATE_MAX_LIFE = () => ConvertUnitState(1);
export const UNIT_STATE_MANA = () => ConvertUnitState(2);
export const UNIT_STATE_MAX_MANA = () => ConvertUnitState(3);
export const UNIT_STATE_ATTACK_DICE = () => ConvertUnitState(0x10);
export const UNIT_STATE_ATTACK_SIDE = () => ConvertUnitState(0x11);
export const UNIT_STATE_ATTACK_WHITE = () => ConvertUnitState(0x12);
export const UNIT_STATE_ATTACK_BONUS = () => ConvertUnitState(0x13);
export const UNIT_STATE_ATTACK_MIX = () => ConvertUnitState(0x14);
export const UNIT_STATE_ATTACK_MAX = () => ConvertUnitState(0x15);
export const UNIT_STATE_ATTACK_RANGE = () => ConvertUnitState(0x16);
export const UNIT_STATE_DEFEND_WHITE = () => ConvertUnitState(0x20);
export const UNIT_STATE_ATTACK_SPACE = () => ConvertUnitState(0x25);
export const UNIT_STATE_ATTACK_SPEED = () => ConvertUnitState(0x51);
export const AI_DIFFICULTY_NEWBIE = () => ConvertAIDifficulty(0);
export const AI_DIFFICULTY_NORMAL = () => ConvertAIDifficulty(1);
export const AI_DIFFICULTY_INSANE = () => ConvertAIDifficulty(2);
export const PLAYER_SCORE_UNITS_TRAINED = () => ConvertPlayerScore(0);
export const PLAYER_SCORE_UNITS_KILLED = () => ConvertPlayerScore(1);
export const PLAYER_SCORE_STRUCT_BUILT = () => ConvertPlayerScore(2);
export const PLAYER_SCORE_STRUCT_RAZED = () => ConvertPlayerScore(3);
export const PLAYER_SCORE_TECH_PERCENT = () => ConvertPlayerScore(4);
export const PLAYER_SCORE_FOOD_MAXPROD = () => ConvertPlayerScore(5);
export const PLAYER_SCORE_FOOD_MAXUSED = () => ConvertPlayerScore(6);
export const PLAYER_SCORE_HEROES_KILLED = () => ConvertPlayerScore(7);
export const PLAYER_SCORE_ITEMS_GAINED = () => ConvertPlayerScore(8);
export const PLAYER_SCORE_MERCS_HIRED = () => ConvertPlayerScore(9);
export const PLAYER_SCORE_GOLD_MINED_TOTAL = () => ConvertPlayerScore(10);
export const PLAYER_SCORE_GOLD_MINED_UPKEEP = () => ConvertPlayerScore(11);
export const PLAYER_SCORE_GOLD_LOST_UPKEEP = () => ConvertPlayerScore(12);
export const PLAYER_SCORE_GOLD_LOST_TAX = () => ConvertPlayerScore(13);
export const PLAYER_SCORE_GOLD_GIVEN = () => ConvertPlayerScore(14);
export const PLAYER_SCORE_GOLD_RECEIVED = () => ConvertPlayerScore(15);
export const PLAYER_SCORE_LUMBER_TOTAL = () => ConvertPlayerScore(16);
export const PLAYER_SCORE_LUMBER_LOST_UPKEEP = () => ConvertPlayerScore(17);
export const PLAYER_SCORE_LUMBER_LOST_TAX = () => ConvertPlayerScore(18);
export const PLAYER_SCORE_LUMBER_GIVEN = () => ConvertPlayerScore(19);
export const PLAYER_SCORE_LUMBER_RECEIVED = () => ConvertPlayerScore(20);
export const PLAYER_SCORE_UNIT_TOTAL = () => ConvertPlayerScore(21);
export const PLAYER_SCORE_HERO_TOTAL = () => ConvertPlayerScore(22);
export const PLAYER_SCORE_RESOURCE_TOTAL = () => ConvertPlayerScore(23);
export const PLAYER_SCORE_TOTAL = () => ConvertPlayerScore(24);
export const EVENT_GAME_VICTORY = () => ConvertGameEvent(0);
export const EVENT_GAME_END_LEVEL = () => ConvertGameEvent(1);
export const EVENT_GAME_VARIABLE_LIMIT = () => ConvertGameEvent(2);
export const EVENT_GAME_STATE_LIMIT = () => ConvertGameEvent(3);
export const EVENT_GAME_TIMER_EXPIRED = () => ConvertGameEvent(4);
export const EVENT_GAME_ENTER_REGION = () => ConvertGameEvent(5);
export const EVENT_GAME_LEAVE_REGION = () => ConvertGameEvent(6);
export const EVENT_GAME_TRACKABLE_HIT = () => ConvertGameEvent(7);
export const EVENT_GAME_TRACKABLE_TRACK = () => ConvertGameEvent(8);
export const EVENT_GAME_SHOW_SKILL = () => ConvertGameEvent(9);
export const EVENT_GAME_BUILD_SUBMENU = () => ConvertGameEvent(10);
export const EVENT_PLAYER_STATE_LIMIT = () => ConvertPlayerEvent(11);
export const EVENT_PLAYER_ALLIANCE_CHANGED = () => ConvertPlayerEvent(12);
export const EVENT_PLAYER_DEFEAT = () => ConvertPlayerEvent(13);
export const EVENT_PLAYER_VICTORY = () => ConvertPlayerEvent(14);
export const EVENT_PLAYER_LEAVE = () => ConvertPlayerEvent(15);
export const EVENT_PLAYER_CHAT = () => ConvertPlayerEvent(16);
export const EVENT_PLAYER_END_CINEMATIC = () => ConvertPlayerEvent(17);
export const EVENT_PLAYER_UNIT_ATTACKED = () => ConvertPlayerUnitEvent(18);
export const EVENT_PLAYER_UNIT_RESCUED = () => ConvertPlayerUnitEvent(19);
export const EVENT_PLAYER_UNIT_DEATH = () => ConvertPlayerUnitEvent(20);
export const EVENT_PLAYER_UNIT_DECAY = () => ConvertPlayerUnitEvent(21);
export const EVENT_PLAYER_UNIT_DETECTED = () => ConvertPlayerUnitEvent(22);
export const EVENT_PLAYER_UNIT_HIDDEN = () => ConvertPlayerUnitEvent(23);
export const EVENT_PLAYER_UNIT_SELECTED = () => ConvertPlayerUnitEvent(24);
export const EVENT_PLAYER_UNIT_DESELECTED = () => ConvertPlayerUnitEvent(25);
export const EVENT_PLAYER_UNIT_CONSTRUCT_START = () => ConvertPlayerUnitEvent(26);
export const EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL = () => ConvertPlayerUnitEvent(27);
export const EVENT_PLAYER_UNIT_CONSTRUCT_FINISH = () => ConvertPlayerUnitEvent(28);
export const EVENT_PLAYER_UNIT_UPGRADE_START = () => ConvertPlayerUnitEvent(29);
export const EVENT_PLAYER_UNIT_UPGRADE_CANCEL = () => ConvertPlayerUnitEvent(30);
export const EVENT_PLAYER_UNIT_UPGRADE_FINISH = () => ConvertPlayerUnitEvent(31);
export const EVENT_PLAYER_UNIT_TRAIN_START = () => ConvertPlayerUnitEvent(32);
export const EVENT_PLAYER_UNIT_TRAIN_CANCEL = () => ConvertPlayerUnitEvent(33);
export const EVENT_PLAYER_UNIT_TRAIN_FINISH = () => ConvertPlayerUnitEvent(34);
export const EVENT_PLAYER_UNIT_RESEARCH_START = () => ConvertPlayerUnitEvent(35);
export const EVENT_PLAYER_UNIT_RESEARCH_CANCEL = () => ConvertPlayerUnitEvent(36);
export const EVENT_PLAYER_UNIT_RESEARCH_FINISH = () => ConvertPlayerUnitEvent(37);
export const EVENT_PLAYER_UNIT_ISSUED_ORDER = () => ConvertPlayerUnitEvent(38);
export const EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER = () => ConvertPlayerUnitEvent(39);
export const EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER = () => ConvertPlayerUnitEvent(40);
export const EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER = () => ConvertPlayerUnitEvent(40);
export const EVENT_PLAYER_HERO_LEVEL = () => ConvertPlayerUnitEvent(41);
export const EVENT_PLAYER_HERO_SKILL = () => ConvertPlayerUnitEvent(42);
export const EVENT_PLAYER_HERO_REVIVABLE = () => ConvertPlayerUnitEvent(43);
export const EVENT_PLAYER_HERO_REVIVE_START = () => ConvertPlayerUnitEvent(44);
export const EVENT_PLAYER_HERO_REVIVE_CANCEL = () => ConvertPlayerUnitEvent(45);
export const EVENT_PLAYER_HERO_REVIVE_FINISH = () => ConvertPlayerUnitEvent(46);
export const EVENT_PLAYER_UNIT_SUMMON = () => ConvertPlayerUnitEvent(47);
export const EVENT_PLAYER_UNIT_DROP_ITEM = () => ConvertPlayerUnitEvent(48);
export const EVENT_PLAYER_UNIT_PICKUP_ITEM = () => ConvertPlayerUnitEvent(49);
export const EVENT_PLAYER_UNIT_USE_ITEM = () => ConvertPlayerUnitEvent(50);
export const EVENT_PLAYER_UNIT_LOADED = () => ConvertPlayerUnitEvent(51);
export const EVENT_UNIT_DAMAGED = () => ConvertUnitEvent(52);
export const EVENT_UNIT_DEATH = () => ConvertUnitEvent(53);
export const EVENT_UNIT_DECAY = () => ConvertUnitEvent(54);
export const EVENT_UNIT_DETECTED = () => ConvertUnitEvent(55);
export const EVENT_UNIT_HIDDEN = () => ConvertUnitEvent(56);
export const EVENT_UNIT_SELECTED = () => ConvertUnitEvent(57);
export const EVENT_UNIT_DESELECTED = () => ConvertUnitEvent(58);
export const EVENT_UNIT_STATE_LIMIT = () => ConvertUnitEvent(59);
export const EVENT_UNIT_ACQUIRED_TARGET = () => ConvertUnitEvent(60);
export const EVENT_UNIT_TARGET_IN_RANGE = () => ConvertUnitEvent(61);
export const EVENT_UNIT_ATTACKED = () => ConvertUnitEvent(62);
export const EVENT_UNIT_RESCUED = () => ConvertUnitEvent(63);
export const EVENT_UNIT_CONSTRUCT_CANCEL = () => ConvertUnitEvent(64);
export const EVENT_UNIT_CONSTRUCT_FINISH = () => ConvertUnitEvent(65);
export const EVENT_UNIT_UPGRADE_START = () => ConvertUnitEvent(66);
export const EVENT_UNIT_UPGRADE_CANCEL = () => ConvertUnitEvent(67);
export const EVENT_UNIT_UPGRADE_FINISH = () => ConvertUnitEvent(68);
export const EVENT_UNIT_TRAIN_START = () => ConvertUnitEvent(69);
export const EVENT_UNIT_TRAIN_CANCEL = () => ConvertUnitEvent(70);
export const EVENT_UNIT_TRAIN_FINISH = () => ConvertUnitEvent(71);
export const EVENT_UNIT_RESEARCH_START = () => ConvertUnitEvent(72);
export const EVENT_UNIT_RESEARCH_CANCEL = () => ConvertUnitEvent(73);
export const EVENT_UNIT_RESEARCH_FINISH = () => ConvertUnitEvent(74);
export const EVENT_UNIT_ISSUED_ORDER = () => ConvertUnitEvent(75);
export const EVENT_UNIT_ISSUED_POINT_ORDER = () => ConvertUnitEvent(76);
export const EVENT_UNIT_ISSUED_TARGET_ORDER = () => ConvertUnitEvent(77);
export const EVENT_UNIT_HERO_LEVEL = () => ConvertUnitEvent(78);
export const EVENT_UNIT_HERO_SKILL = () => ConvertUnitEvent(79);
export const EVENT_UNIT_HERO_REVIVABLE = () => ConvertUnitEvent(80);
export const EVENT_UNIT_HERO_REVIVE_START = () => ConvertUnitEvent(81);
export const EVENT_UNIT_HERO_REVIVE_CANCEL = () => ConvertUnitEvent(82);
export const EVENT_UNIT_HERO_REVIVE_FINISH = () => ConvertUnitEvent(83);
export const EVENT_UNIT_SUMMON = () => ConvertUnitEvent(84);
export const EVENT_UNIT_DROP_ITEM = () => ConvertUnitEvent(85);
export const EVENT_UNIT_PICKUP_ITEM = () => ConvertUnitEvent(86);
export const EVENT_UNIT_USE_ITEM = () => ConvertUnitEvent(87);
export const EVENT_UNIT_LOADED = () => ConvertUnitEvent(88);
export const EVENT_WIDGET_DEATH = () => ConvertWidgetEvent(89);
export const EVENT_DIALOG_BUTTON_CLICK = () => ConvertDialogEvent(90);
export const EVENT_DIALOG_CLICK = () => ConvertDialogEvent(91);
export const EVENT_GAME_LOADED = () => ConvertGameEvent(256);
export const EVENT_GAME_TOURNAMENT_FINISH_SOON = () => ConvertGameEvent(257);
export const EVENT_GAME_TOURNAMENT_FINISH_NOW = () => ConvertGameEvent(258);
export const EVENT_GAME_SAVE = () => ConvertGameEvent(259);
export const EVENT_PLAYER_ARROW_LEFT_DOWN = () => ConvertPlayerEvent(261);
export const EVENT_PLAYER_ARROW_LEFT_UP = () => ConvertPlayerEvent(262);
export const EVENT_PLAYER_ARROW_RIGHT_DOWN = () => ConvertPlayerEvent(263);
export const EVENT_PLAYER_ARROW_RIGHT_UP = () => ConvertPlayerEvent(264);
export const EVENT_PLAYER_ARROW_DOWN_DOWN = () => ConvertPlayerEvent(265);
export const EVENT_PLAYER_ARROW_DOWN_UP = () => ConvertPlayerEvent(266);
export const EVENT_PLAYER_ARROW_UP_DOWN = () => ConvertPlayerEvent(267);
export const EVENT_PLAYER_ARROW_UP_UP = () => ConvertPlayerEvent(268);
export const EVENT_PLAYER_UNIT_SELL = () => ConvertPlayerUnitEvent(269);
export const EVENT_PLAYER_UNIT_CHANGE_OWNER = () => ConvertPlayerUnitEvent(270);
export const EVENT_PLAYER_UNIT_SELL_ITEM = () => ConvertPlayerUnitEvent(271);
export const EVENT_PLAYER_UNIT_SPELL_CHANNEL = () => ConvertPlayerUnitEvent(272);
export const EVENT_PLAYER_UNIT_SPELL_CAST = () => ConvertPlayerUnitEvent(273);
export const EVENT_PLAYER_UNIT_SPELL_EFFECT = () => ConvertPlayerUnitEvent(274);
export const EVENT_PLAYER_UNIT_SPELL_FINISH = () => ConvertPlayerUnitEvent(275);
export const EVENT_PLAYER_UNIT_SPELL_ENDCAST = () => ConvertPlayerUnitEvent(276);
export const EVENT_PLAYER_UNIT_PAWN_ITEM = () => ConvertPlayerUnitEvent(277);
export const EVENT_UNIT_SELL = () => ConvertUnitEvent(286);
export const EVENT_UNIT_CHANGE_OWNER = () => ConvertUnitEvent(287);
export const EVENT_UNIT_SELL_ITEM = () => ConvertUnitEvent(288);
export const EVENT_UNIT_SPELL_CHANNEL = () => ConvertUnitEvent(289);
export const EVENT_UNIT_SPELL_CAST = () => ConvertUnitEvent(290);
export const EVENT_UNIT_SPELL_EFFECT = () => ConvertUnitEvent(291);
export const EVENT_UNIT_SPELL_FINISH = () => ConvertUnitEvent(292);
export const EVENT_UNIT_SPELL_ENDCAST = () => ConvertUnitEvent(293);
export const EVENT_UNIT_PAWN_ITEM = () => ConvertUnitEvent(294);
export const LESS_THAN = () => ConvertLimitOp(0);
export const LESS_THAN_OR_EQUAL = () => ConvertLimitOp(1);
export const EQUAL = () => ConvertLimitOp(2);
export const GREATER_THAN_OR_EQUAL = () => ConvertLimitOp(3);
export const GREATER_THAN = () => ConvertLimitOp(4);
export const NOT_EQUAL = () => ConvertLimitOp(5);
export const UNIT_TYPE_HERO = () => ConvertUnitType(0);
export const UNIT_TYPE_DEAD = () => ConvertUnitType(1);
export const UNIT_TYPE_STRUCTURE = () => ConvertUnitType(2);
export const UNIT_TYPE_FLYING = () => ConvertUnitType(3);
export const UNIT_TYPE_GROUND = () => ConvertUnitType(4);
export const UNIT_TYPE_ATTACKS_FLYING = () => ConvertUnitType(5);
export const UNIT_TYPE_ATTACKS_GROUND = () => ConvertUnitType(6);
export const UNIT_TYPE_MELEE_ATTACKER = () => ConvertUnitType(7);
export const UNIT_TYPE_RANGED_ATTACKER = () => ConvertUnitType(8);
export const UNIT_TYPE_GIANT = () => ConvertUnitType(9);
export const UNIT_TYPE_SUMMONED = () => ConvertUnitType(10);
export const UNIT_TYPE_STUNNED = () => ConvertUnitType(11);
export const UNIT_TYPE_PLAGUED = () => ConvertUnitType(12);
export const UNIT_TYPE_SNARED = () => ConvertUnitType(13);
export const UNIT_TYPE_UNDEAD = () => ConvertUnitType(14);
export const UNIT_TYPE_MECHANICAL = () => ConvertUnitType(15);
export const UNIT_TYPE_PEON = () => ConvertUnitType(16);
export const UNIT_TYPE_SAPPER = () => ConvertUnitType(17);
export const UNIT_TYPE_TOWNHALL = () => ConvertUnitType(18);
export const UNIT_TYPE_ANCIENT = () => ConvertUnitType(19);
export const UNIT_TYPE_TAUREN = () => ConvertUnitType(20);
export const UNIT_TYPE_POISONED = () => ConvertUnitType(21);
export const UNIT_TYPE_POLYMORPHED = () => ConvertUnitType(22);
export const UNIT_TYPE_SLEEPING = () => ConvertUnitType(23);
export const UNIT_TYPE_RESISTANT = () => ConvertUnitType(24);
export const UNIT_TYPE_ETHEREAL = () => ConvertUnitType(25);
export const UNIT_TYPE_MAGIC_IMMUNE = () => ConvertUnitType(26);
export const ITEM_TYPE_PERMANENT = () => ConvertItemType(0);
export const ITEM_TYPE_CHARGED = () => ConvertItemType(1);
export const ITEM_TYPE_POWERUP = () => ConvertItemType(2);
export const ITEM_TYPE_ARTIFACT = () => ConvertItemType(3);
export const ITEM_TYPE_PURCHASABLE = () => ConvertItemType(4);
export const ITEM_TYPE_CAMPAIGN = () => ConvertItemType(5);
export const ITEM_TYPE_MISCELLANEOUS = () => ConvertItemType(6);
export const ITEM_TYPE_UNKNOWN = () => ConvertItemType(7);
export const ITEM_TYPE_ANY = () => ConvertItemType(8);
export const ITEM_TYPE_TOME = () => ConvertItemType(2);
export const CAMERA_FIELD_TARGET_DISTANCE = () => ConvertCameraField(0);
export const CAMERA_FIELD_FARZ = () => ConvertCameraField(1);
export const CAMERA_FIELD_ANGLE_OF_ATTACK = () => ConvertCameraField(2);
export const CAMERA_FIELD_FIELD_OF_VIEW = () => ConvertCameraField(3);
export const CAMERA_FIELD_ROLL = () => ConvertCameraField(4);
export const CAMERA_FIELD_ROTATION = () => ConvertCameraField(5);
export const CAMERA_FIELD_ZOFFSET = () => ConvertCameraField(6);
export const BLEND_MODE_NONE = () => ConvertBlendMode(0);
export const BLEND_MODE_DONT_CARE = () => ConvertBlendMode(0);
export const BLEND_MODE_KEYALPHA = () => ConvertBlendMode(1);
export const BLEND_MODE_BLEND = () => ConvertBlendMode(2);
export const BLEND_MODE_ADDITIVE = () => ConvertBlendMode(3);
export const BLEND_MODE_MODULATE = () => ConvertBlendMode(4);
export const BLEND_MODE_MODULATE_2X = () => ConvertBlendMode(5);
export const RARITY_FREQUENT = () => ConvertRarityControl(0);
export const RARITY_RARE = () => ConvertRarityControl(1);
export const TEXMAP_FLAG_NONE = () => ConvertTexMapFlags(0);
export const TEXMAP_FLAG_WRAP_U = () => ConvertTexMapFlags(1);
export const TEXMAP_FLAG_WRAP_V = () => ConvertTexMapFlags(2);
export const TEXMAP_FLAG_WRAP_UV = () => ConvertTexMapFlags(3);
export const FOG_OF_WAR_MASKED = () => ConvertFogState(1);
export const FOG_OF_WAR_FOGGED = () => ConvertFogState(2);
export const FOG_OF_WAR_VISIBLE = () => ConvertFogState(4);
export const CAMERA_MARGIN_LEFT = 0;
export const CAMERA_MARGIN_RIGHT = 1;
export const CAMERA_MARGIN_TOP = 2;
export const CAMERA_MARGIN_BOTTOM = 3;
export const EFFECT_TYPE_EFFECT = () => ConvertEffectType(0);
export const EFFECT_TYPE_TARGET = () => ConvertEffectType(1);
export const EFFECT_TYPE_CASTER = () => ConvertEffectType(2);
export const EFFECT_TYPE_SPECIAL = () => ConvertEffectType(3);
export const EFFECT_TYPE_AREA_EFFECT = () => ConvertEffectType(4);
export const EFFECT_TYPE_MISSILE = () => ConvertEffectType(5);
export const EFFECT_TYPE_LIGHTNING = () => ConvertEffectType(6);
export const SOUND_TYPE_EFFECT = () => ConvertSoundType(0);
export const SOUND_TYPE_EFFECT_LOOPED = () => ConvertSoundType(1);
export const EVENT_DAMAGE_DATA_VAILD = 0;
export const EVENT_DAMAGE_DATA_IS_PHYSICAL = 1;
export const EVENT_DAMAGE_DATA_IS_ATTACK = 2;
export const EVENT_DAMAGE_DATA_IS_RANGED = 3;
export const EVENT_DAMAGE_DATA_DAMAGE_TYPE = 4;
export const EVENT_DAMAGE_DATA_WEAPON_TYPE = 5;
export const EVENT_DAMAGE_DATA_ATTACK_TYPE = 6;
export const MOVE_TYPE_NONE = 0x00;
export const MOVE_TYPE_NOT = 0x01;
export const MOVE_TYPE_FOOT = 0x02;
export const MOVE_TYPE_FLY = 0x04;
export const MOVE_TYPE_MINE = 0x08;
export const MOVE_TYPE_WIND = 0x10;
export const MOVE_TYPE_UN = 0x20;
export const MOVE_TYPE_FLOAT = 0x40;
export const MOVE_TYPE_AMPH = 0x80;
export const COLLISION_TYPE_UNIT = 1;
export const COLLISION_TYPE_BUILDING = 3;

export const FRAME_ALIGN_LEFT_TOP = 0;
export const FRAME_ALIGN_TOP = 1;
export const FRAME_ALIGN_RIGHT_TOP = 2;
export const FRAME_ALIGN_LEFT = 3;
export const FRAME_ALIGN_CENTER = 4;
export const FRAME_ALIGN_RIGHT = 5;
export const FRAME_ALIGN_LEFT_BOTTOM = 6;
export const FRAME_ALIGN_BOTTOM = 7;
export const FRAME_ALIGN_RIGHT_BOTTOM = 8;

export const FRAMEPOINT_BOTTOM = 7;
export const FRAMEPOINT_BOTTOMLEFT = 6;
export const FRAMEPOINT_BOTTOMRIGHT = 8;
export const FRAMEPOINT_CENTER = 4;
export const FRAMEPOINT_LEFT = 3;
export const FRAMEPOINT_RIGHT = 5;
export const FRAMEPOINT_TOP = 1;
export const FRAMEPOINT_TOPLEFT = 0;
export const FRAMEPOINT_TOPRIGHT = 2;

export const MOUSE_ORDER_CLICK = 1;
export const MOUSE_ORDER_ENTER = 2;
export const MOUSE_ORDER_LEAVE = 3;
export const MOUSE_ORDER_RELEASE = 4;
export const MOUSE_ORDER_SCROLL = 6;
export const MOUSE_ORDER_DOUBLE_CLICK = 12;
export const GAME_KEY_MOUSE_LEFT = 1;
export const GAME_KEY_MOUSE_RIGHT = 2;
export const GAME_KEY_A = 65;
export const GAME_KEY_B = 66;
export const GAME_KEY_C = 67;
export const GAME_KEY_D = 68;
export const GAME_KEY_E = 69;
export const GAME_KEY_F = 70;
export const GAME_KEY_G = 71;
export const GAME_KEY_H = 72;
export const GAME_KEY_I = 73;
export const GAME_KEY_J = 74;
export const GAME_KEY_K = 75;
export const GAME_KEY_L = 76;
export const GAME_KEY_M = 77;
export const GAME_KEY_N = 78;
export const GAME_KEY_O = 79;
export const GAME_KEY_P = 80;
export const GAME_KEY_Q = 81;
export const GAME_KEY_R = 82;
export const GAME_KEY_S = 83;
export const GAME_KEY_T = 84;
export const GAME_KEY_U = 85;
export const GAME_KEY_V = 86;
export const GAME_KEY_W = 87;
export const GAME_KEY_X = 88;
export const GAME_KEY_Y = 89;
export const GAME_KEY_Z = 90;
export const GAME_KEY_0 = 48;
export const GAME_KEY_1 = 49;
export const GAME_KEY_2 = 50;
export const GAME_KEY_3 = 51;
export const GAME_KEY_4 = 52;
export const GAME_KEY_5 = 53;
export const GAME_KEY_6 = 54;
export const GAME_KEY_7 = 55;
export const GAME_KEY_8 = 56;
export const GAME_KEY_9 = 57;
export const GAME_KEY_TAB = 9;
export const GAME_KEY_SPACE = 32;
export const GAME_KEY_ENTER = 513;
export const GAME_KEY_BACKSPACE = 514;
export const GAME_KEY_SHIFT = 0;
export const GAME_KEY_RIGHT = 516;
export const GAME_KEY_UP = 517;
export const GAME_KEY_LEFT = 518;
export const GAME_KEY_DOWN = 519;
export const GAME_KEY_ACTION_PRESS = 1;
export const GAME_KEY_ACTION_RELEASE = 0;
export const TEXT_ALIGN_LEFT_TOP = 11;
export const TEXT_ALIGN_TOP = 17;
export const TEXT_ALIGN_RIGHT_TOP = 37;
export const TEXT_ALIGN_CENTER = 18;
export const TEXT_ALIGN_LEFT = 10;
export const TEXT_ALIGN_RIGHT = 34;
export const TEXT_ALIGN_LEFT_BOTTOM = 12;
export const TEXT_ALIGN_BOTTOM = 20;
export const TEXT_ALIGN_RIGHT_BOTTOM = 36;
